# Generated by Django 4.1.7 on 2023-03-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("department", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="departmentmodel",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
